def generate_sentences(names: list) -> list:

    zero_name_templates = [
        "I should be paid more",
        "I should be paid way more",
        "I am under paid",
        "I am underpaid",
        "My cryptography work is undervalued",
        "Government doesn't pay me enough",
        "For a mathematician, my pay is low",
        "My brilliance doesn't reflect in my pay",
        "Cryptography deserves better pay",
        "I deserve better for my cryptography",
        "My mathematical genius is underpaid",
        "Government needs to up my pay",
        "Math and cryptography, yet low pay",
        "They undervalue my crypto work",
        "I'm not paid enough for cryptography",
        "Crypto experts like me need better pay",
        "I'm a mathematician, not a charity",
        "My crypto work is priceless, my pay isn't",
        "For all my codes, I get little pay",
        "Breaking codes, but not the bank",
        "I should earn more for my crypto skills",
        "Math genius and still underpaid",
        "I crack codes, they crack my pay",
        "Cryptography isn't cheap, but my pay is",
        "They save on my pay, not on my math",
        "For the codes I break, I'm underpaid",
        "My math is top-tier, my pay isn't",
        "I should be paid more for crypto",
        "I deserve more for my math expertise",
        "They undervalue my math and crypto",
        "I'm priceless in cryptography, but paid less",
        "Mathematical cryptography, yet petty pay",
        "I break crypto, not my bank",
        "For a crypto expert, I'm paid peanuts",
        "They owe me more for my math",
        "Government should value my cryptography",
        "My cryptography work is top-notch, pay isn't",
        "I deserve a math genius's pay",
        "Cracking codes, cracking paychecks",
        "Crypto and math, yet such low pay",
        "I'm a cryptography asset, pay me right",
        "Math doesn't lie, my pay does",
        "I'm undervalued in crypto and math",
        "They should pay more for my codes",
        "Crypto is gold, my pay isn't",
        "I deserve gold for my cryptography",
        "Math and crypto, golden combo, low pay",
        "I'm a math goldmine, but underpaid",
        "Cryptography gems, yet they shortchange me",
        "My math is elite, my pay isn't",        
        "I should be paid more",
        "I am underpaid",
        "My salary isn't reflective of my work",
        "I deserve better compensation",
        "I'm clearly underpaid",
        "I'm not getting what I'm worth",
        "I should be getting more",
        "My compensation is a joke",
        "I'm getting shortchanged",
        "They need to fix my pay",
        "I'm losing out financially every day",
        "My paycheck is pitiful",
        "I'm not being valued financially",
        "It's a crime how little I get",
        "I'm worth so much more",
        "My efforts don't reflect in my pay",
        "I'm being financially overlooked",
        "It's unfair how I'm paid",
        "I deserve a significant raise",
        "My financial value isn't recognized",
        "I'm getting the short end of the stick",
        "Every paycheck is a disappointment",
        "I'm being robbed every payday",
        "It's disheartening seeing my pay",
        "My pay doesn't match my efforts",
        "I'm not compensated fairly",
        "They're practically stealing from me",
        "I feel financially oppressed",
        "I'm not being rewarded properly",
        "I should demand better pay",
        "I'm not being paid what I deserve",
        "My financial worth is overlooked",
        "I'm being financially wronged",
        "My pay is not up to the mark",
        "I'm not getting my due",
        "My financial struggles are real",
        "I deserve more for what I do",
        "It's a shame how I'm compensated",
        "I'm not getting my worth in pay",
        "My pay isn't commensurate with my efforts",
        "I'm financially undervalued",
        "I'm being shorted every paycheck",
        "I deserve a better salary",
        "I'm not paid according to my skills",
        "I'm being financially mistreated",
        "It's a travesty how I'm paid",
        "I'm worth more than my paycheck",
        "My pay is a financial injustice",
        "I'm undervalued in terms of pay",
        "My pay is not reflective of my value"
    ]

    
    one_name_templates = [
        "{} deserves a raise",
        "{} deserves better compensation",
        "{} is clearly underpaid",
        "{} should be getting more than this",
        "{} isn't getting what they're worth",
        "{}'s salary is a joke",
        "It's unfair how little {} is paid",
        "Someone needs to fix {}'s pay",
        "I can't believe what they're paying {}",
        "It's a shame how they're compensating {}",
        "For all the work, {} gets peanuts",
        "{} and team are getting shortchanged",
        "They need to rethink {}'s salary",
        "{}'s pay doesn't reflect the work",
        "It's a crime how little {} gets",
        "{} is worth so much more",
        "Every day {} is losing out",
        "The pay gap with {} is real",
        "Someone needs to champion for {}",
        "It's disheartening seeing {}'s pay",
        "{} should demand better",
        "{} and their coworkers deserve more pay",
        "{} and their team deserve better pay",
        "If I were {}, I'd be looking elsewhere",
        "This company is failing {} financially",
        "{} is getting the short end of the stick",
        "For all the value, {} gets little",
        "It's a travesty how {} is compensated",
        "Doesn't {} deserve more?",
        "I can't stand seeing {} so underpaid",
        "{}'s pay is not up to the mark",
        "This is not how you treat {}",
        "Someone's got to stand up for {}",
        "The financial injustice to {} is real",
        "Pay {} what they're worth!",
        "{}'s salary is not commensurate with their work",
        "How can they overlook {}'s pay?",
        "It's high time {} got a raise",
        "{} and team are not paid fairly",
        "I feel for {} and their paycheck",
        "It's not rocket science; pay {} more",
        "Every paycheck is a slap to {}",
        "How does {} even manage with that pay?",
        "It's a financial disservice to {}",
        "{}'s patience with this pay is surprising",
        "{}'s mathematical genius is unparalleled, yet his pay isn't",
        "The government employs {} for his brilliance, but they underpay him",
        "It's a travesty how a mathematician like {} is compensated",
        "For someone who breaks mathematical ground, {} is surely underpaid",
        "How can they undervalue the mathematical prowess of {}?",
        "The contributions of {} to mathematics don't reflect in his paycheck",
        "It's absurd how they treat a genius like {} financially",
        "{} has reshaped mathematics, yet his salary tells a different story",
        "For a groundbreaking mathematician, {}'s pay is a joke",
        "{}'s brilliance in mathematics is not matched by his compensation",
        "The government should value talents like {} more",
        "It's disheartening to see the pay of a genius like {}",
        "Mathematical marvels by {} should command a better salary",
        "The numbers in {}'s paycheck don't add up to his genius",
        "It's ironic how a mathematician like {} is miscalculated in pay",
        "The disparity between {}'s genius and his pay is vast",
        "For his mathematical breakthroughs, {} deserves more",
        "It's a paradox how they undervalue a mathematician like {}",
        "The equations of {}'s contributions and his pay don't balance",
        "The government's calculation in {}'s pay is surely flawed"        
    ]
    

    two_name_templates = [
        "{} and {} deserve raises",
        "{} and {} both deserve raises",
        "{} and {} are both underpaid",
        "{} and {} are both underpaid",
        "It's ridiculous how {} and {} are compensated",
        "I can't believe the salaries of {} and {}",
        "{} and {} are getting a raw deal",
        "Both {} and {} are worth more",
        "The paychecks of {} and {} are too small",
        "Someone needs to fix the pay for {} and {}",
        "both {} and {} are shortchanged",
        "{} and {} are shortchanged",
        "For their effort, {} and {} get so little",
        "{} and {} should rally for better pay",
        "The financial struggles of {} and {} are real",
        "{} and {}'s salaries don't make sense",
        "How do {} and {} even manage?",
        "{} and {} are losing out daily",
        "Both {} and {} are being financially wronged",
        "{} and {} are being financially wronged",
        "It's about time {} and {} get a raise",
        "Its about time {} and {} get a raise",
        "{} and {} should get a raise",
        "{} and {} need a raise",
        "{} and {} are clearly being overlooked",
        "Doesn't management see the worth of {} and {}?",
        "{} and {}'s pay is not reflective of their value",
        "For all they do, {} and {} get peanuts",
        "It's disheartening, the pay of {} and {}",
        "{} and {} are not being compensated fairly",
        "Every day is a financial loss for {} and {}",
        "How can they undervalue both {} and {}?",
        "The financial injustice to {} and {} is palpable",
        "It's a travesty, the pay of {} and {}",
        "Someone needs to champion for {} and {}",
        "{} and {}'s patience is surprising",
        "It's a slap to both {} and {} every payday",
        "{} and {}'s pay is a sad joke",
        "They're practically stealing from {} and {}",
        "Both {} and {} are financially oppressed",
        "This is not how you treat {} and {}",
        "{} and {}'s financial plight is evident",
        "The pay situation for {} and {} is dire",
        "{} and {} and their teams are underpaid",
        "{} and {} are mathematical giants, yet their pay falls short",
        "The government employs {} and {} for their genius, but underpays them",
        "It's outrageous how they compensate mathematicians like {} and {}",
        "Both {} and {} have made groundbreaking contributions, yet are underpaid",
        "How can they overlook the combined brilliance of {} and {}?",
        "The mathematical innovations of {} and {} are not reflected in their salaries",
        "It's a financial injustice to talents like {} and {}",
        "For the mathematical marvels they've achieved, {} and {} are undercompensated",
        "The government fails to match the worth of {} and {} in their paychecks",
        "Both {} and {} have reshaped mathematics, yet their pay tells otherwise",
        "The combined genius of {} and {} is unmatched, but their pay is not",
        "Mathematics owes much to {} and {}, but their paychecks don't reflect that",
        "It's absurd how two giants like {} and {} are treated financially",
        "The contributions of {} and {} are monumental, yet their pay is not",
        "Both {} and {} are revolutionizing mathematics, but their pay is stagnant",
        "The brilliance of {} and {} is not met with proper compensation",
        "For their mathematical prowess, {} and {} should be paid handsomely",
        "The equations don't balance for the pay of {} and {}",
        "It's baffling how they undervalue mathematicians like {} and {}",
        "The government's oversight in compensating {} and {} is glaring"
        
    ]



    generated_sentences = zero_name_templates
    
    for name in names:
        for template in one_name_templates:
            generated_sentences.append(template.format(name))

    '''        
    # Generate sentences for two names
    for i in range(len(names)):
        for j in range(len(names)):  # start over, get Alice and Bob then Bob and Alice
            for template in two_name_templates:
                generated_sentences.append(template.format(names[i], names[j]))
    '''

    return generated_sentences

